site_name: cau-repl
# TODO site_url: ''
repo_url: 'https://github.com/os-cau/cau-repl'
site_description: 'Documentation for the cau-repl software'
nav:
  - About: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Using the REPL: repl.md
extra_css:
  - custom.css
remote_branch: gh-pages
remote_name: github
theme:
  name: readthedocs
  locale: en
# strict: true
dev_addr: '127.0.0.1:8088'